### ISSUE TITLE
 - Security Remediation

### ISSUE THREAD

**Issue by ayasuda2OO3** [EC-Release/web-ui#14]
Following by the recommendation by github, some update(s) awaits to address the security items below-

https://github.com/Enterprise-connect/web-ui/network/alerts

Please review submit remediation. @iamkoushikpal-ge

**Comment by iamkoushikpal-ge** [comment]
@ayasuda2003 https://github.com/Enterprise-connect/web-ui/network/alerts this link is showing 404 not found for me.

**Comment by ayasuda2OO3** [comment]
> @ayasuda2003 https://github.com/Enterprise-connect/web-ui/network/alerts this link is showing 404 not found for me.

Invitation was sent. Please acknowledge. @iamkoushikpal-ge

**Comment by iamkoushikpal-ge** [comment]
![image](https://user-images.githubusercontent.com/60262022/78532983-c8f6ab80-7805-11ea-9f4c-1c399eeb0da4.png)

Still not accessible @ayasuda2003

**Comment by iamkoushikpal-ge** [comment]
It is now accessible and also worked on it today. @ayasuda2003

**Comment by ayasuda2OO3** [comment]
Fixed and merged @palokam
