### ISSUE TITLE
Static account fix

### ISSUE THREAD

**Issue by Gayatri212** [EC-Release/web-ui#16]
This line shows the data is fetched for only one fixed account
https://github.com/Enterprise-connect/web-ui/blob/v1.1beta/webui-assets/App.js#L46

Please make it dynamic.

**Comment by iamkoushikpal-ge** [comment]
@Gayatri212 As discussed Please provide me an API endpoint so that I can make it dynamic.

**Comment by iamkoushikpal-ge** [comment]
Frontend code is done but we can test it when Agent will be available with this API endpoint
