### ISSUE TITLE
xclar dependecy is a problem for WebUi to work independently.

### ISSUE THREAD

**Issue by palokam** [EC-Release/web-ui#41]
As webui oauth is tightly integrated with the Xscalr in the background, how do we ensure that xscalr is up and running which internally reflects back to WEBUI Health.

Comments - Xscalr was down for 2 days when i was working on the EC Console operationalization. Got to know this issue after reaching out to EC Engineering team.

**Comment by ayasuda2OO3** [comment]
issue has been resolved. please work with PMs/POs for potential feature request.

This tracker may remain open in next three days for further justification. @Gayatri21 @ramaraosrikakulapu
