### ISSUE TITLE
Implement logout landing page.

### ISSUE THREAD

**Issue by iamkoushikpal-ge** [EC-Release/web-ui#49]
Implement logout landing html page.

**Comment by ayasuda2OO3** [comment]
@iamkoushikpal-ge 
Please update the usage of logout 
from:
```/v1.1beta/ec/logout```
to
```/v1.1beta/logout```

This is to address all relevant app cookies setting for security. FYI @Gayatri212

**Comment by ayasuda2OO3** [comment]
The url did not update as proposed @iamkoushikpal-ge 
from:
```/v1.1beta/ec/logout```
to
```/v1.1beta/logout```

URL: https://ec-webui.herokuapp.com/v1.1beta/logout
![Screenshot from 2020-04-29 22-58-36](https://user-images.githubusercontent.com/552253/80677060-04833f00-8a6d-11ea-993c-2a7516f6edab.png)

URL: https://ec-webui.herokuapp.com/v1.1beta/ec
![Screenshot from 2020-04-29 22-58-04](https://user-images.githubusercontent.com/552253/80677064-064d0280-8a6d-11ea-9163-7dcc4f9e9573.png)

**Comment by Gayatri212** [comment]
Issue has been fixed and pushed the fixed code. [Link to PR](https://github.com/Enterprise-connect/web-ui/pull/51)
